version: '3'

services:
  x-clone-prod:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: x-clone
    hostname: x-clone
    environment:
      - MONGO_URI=${MONGO_URI_PROD}
      - PORT=${APP_PORT}
      - JWT_SECRET=${JWT_SECRET_PROD}
      - NODE_ENV=${NODE_ENV_PROD}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - x_net

networks:
  x_net:
    driver: bridge
    name: x_net