version: '3'

services:
  x-clone-stg:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: x-clone
    hostname: x-clone
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - x_net

networks:
  x_net:
    driver: bridge
    name: x_net