version: '3'

services:
  x-clone-stg:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: x-clone
    hostname: x-clone
    environment:
      - MONGO_URI=${MONGO_URI_STG}
      - PORT=${APP_PORT}
      - JWT_SECRET=${JWT_SECRET_STG}
      - NODE_ENV=${NODE_ENV_STG}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - x_net

networks:
  x_net:
    driver: bridge
    name: x_net