version: '3'

services:
  x-clone:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: rahilpacmann/x-clone:0.0.1
    container_name: x-clone
    hostname: x-clone
    environment:
      - MONGO_URI=${MONGO_URI_DEV}
      - PORT=${APP_PORT}
      - JWT_SECRET=${JWT_SECRET_DEV}
      - NODE_ENV=${NODE_ENV_DEV}
    depends_on:
      - mongodb
      - mongo-ui
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - x_net

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_DEV}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD_DEV}
    volumes:
      - mongodb_data:/data/db
    networks:
      - x_net

  mongo-ui:
    image: mongo-express
    container_name: mongo-ui
    hostname: mongo-ui
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER_DEV}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD_DEV}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI_DEV}
      ME_CONFIG_BASICAUTH: false
    networks:
      - x_net

networks:
  x_net:
    driver: bridge
    name: x_net

volumes:
  mongodb_data:
    driver: local
    name: mongodb_data