version: '3'

services:
  x-clone:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: rahilpacmann/x-clone:0.0.1
    container_name: x-clone
    hostname: x-clone
    depends_on:
      - mongodb
      - mongo-ui
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - x_net

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - x_net

  mongo-ui:
    image: mongo-express
    container_name: mongo-ui
    hostname: mongo-ui
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
      ME_CONFIG_BASICAUTH: false
    networks:
      - x_net

networks:
  x_net:
    driver: bridge
    name: x_net

volumes:
  mongodb_data:
    driver: local
    name: mongodb_data