# This workflow will run automation deployment to production servers.
# Triggers : Publish the release app or edit the latest release
name: Deploy Production 🚀

on:
  release:
    types: 
      - published
      - edited

jobs:
        
  deploy-production:
    name: Deploy to production server 🚀
    runs-on: ubuntu-latest
    environment: production
    steps:
        - name: Execute deployment command
          uses: appleboy/ssh-action@v1.0.3
          env:
            GIT_URL: ${{ secrets.GIT_URL }}
            MONGO_URI: ${{ secrets.MONGO_URI_PROD }}
            NODE_ENV: ${{ vars.NODE_ENV }}
            APP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/x-clone
            APP_TAG: ${{ github.event.release.tag_name }}
            
          with:
            host: ${{ secrets.SSH_HOST_PRODUCTION }}
            username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
            key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
            envs: GIT_URL, MONGO_URI, NODE_ENV, APP_IMAGE, APP_TAG
            script: |
                echo "Success"