# This workflow will run automation deployment to staging servers.
# Triggers : Push or Merge to Main
# Jobs : Deploy to staging
name: Deploy Staging 🚀

on:
  push:
    branches: [ "main" ]

jobs:
    deploy-staging:
        name: Deploy to staging server
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Execute deployment command
              uses: appleboy/ssh-action@v1.0.3
              env:
                GIT_URL: ${{ secrets.GIT_URL }}
                MONGO_URI: ${{ secrets.MONGO_URI_STG }}
                NODE_ENV: ${{ vars.NODE_ENV }}"
                
              with:
                host: ${{ secrets.SSH_HOST_STAGING }}
                username: ${{ secrets.SSH_USER_NAME_STAGING }}
                key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
                envs: GIT_URL, MONGO_URI, NODE_ENV
                script: |
                  echo "Success"

