# This workflow will run automation build and testing development app.
# Triggers : PR to Main
# Jobs : Build and Testing
name: Dev Testing 🔎

on:
  pull_request:
    branches: ["main"]

jobs:
    build-testing:
        name: Build and Testing
        runs-on: ubuntu-latest
        environment: development
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Create .env file
              run: |
                echo "APP_PORT=${{ secrets.APP_PORT }}" > .env
                echo "NODE_ENV_DEV=${{ vars.NODE_ENV_DEV }}" >> .env
                echo "MONGO_USER_DEV=${{ secrets.MONGO_USER_DEV }}" >> .env
                echo "MONGO_PASSWORD_DEV=${{ secrets.MONGO_PASSWORD_DEV }}" >> .env
                echo "MONGO_URI_DEV=${{ secrets.MONGO_URI_DEV }}" >> .env
                echo "JWT_SECRET_DEV=`openssl rand -base64 32`" >> .env
            
            - name: Run apps
              run: |
                sudo docker compose --file docker-compose.dev.yaml up --build --detach

            - name: Test Hit App Endpoint
              run: |
                sleep 20
                curl http://localhost:5000/
            
            - name: Test Hit Mongo Express Endpoint
              run: |
                sleep 20
                curl http://localhost:8081/

            - name: Install Testing requirements
              run: pip install -r tests/requirements.txt
              
            - name: Testing
              run: python3 tests/main_test.py
